#!/usr/bin/env python3
"""Discover important JSONSchemaBench/MaskBench project files.

This script is intentionally read-only. It scans the repository and writes a
Markdown report under extension_jsonschemabench/reports/.
"""

from __future__ import annotations

import json
import os
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
EXT_ROOT = ROOT / "extension_jsonschemabench"
REPORT_PATH = EXT_ROOT / "reports" / "project_structure_report.md"


def rel(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def count_json_files(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for _ in path.rglob("*.json"))


def direct_json_count(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for _ in path.glob("*.json"))


def load_json(path: Path) -> object | None:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception:
        return None


def discover_result_dirs() -> list[Path]:
    candidates: list[Path] = []
    for base in [ROOT / "tmp", ROOT / "maskbench" / "tmp"]:
        if base.exists():
            candidates.extend(p for p in base.glob("out--*") if p.is_dir())
    return sorted(candidates)


def sample_maskbench_file() -> dict[str, object]:
    data_dir = ROOT / "maskbench" / "data"
    for path in sorted(data_dir.glob("*.json")):
        payload = load_json(path)
        if isinstance(payload, dict):
            tests = payload.get("tests")
            if isinstance(tests, list):
                return {
                    "path": rel(path),
                    "top_level_keys": sorted(payload.keys()),
                    "test_count": len(tests),
                    "first_test_keys": sorted(tests[0].keys()) if tests else [],
                }
    return {}


def main() -> None:
    data_dir = ROOT / "data"
    maskbench_dir = ROOT / "maskbench"
    maskbench_data_dir = maskbench_dir / "data"
    metainfo_dir = maskbench_dir / "metainfo"
    runner_dir = maskbench_dir / "maskbench"
    scripts_dir = maskbench_dir / "scripts"
    creation_dir = maskbench_dir / "creation"

    dataset_counts = []
    if data_dir.exists():
        for child in sorted(p for p in data_dir.iterdir() if p.is_dir()):
            dataset_counts.append((child.name, direct_json_count(child)))

    maskbench_groups: Counter[str] = Counter()
    if maskbench_data_dir.exists():
        for path in maskbench_data_dir.glob("*.json"):
            name = path.name
            if "---" in name:
                group = name.split("---", 1)[0]
            elif name.startswith("BFCL_"):
                group = "BFCL"
            elif name.startswith("JME_"):
                group = "JME"
            else:
                group = name.split("_", 1)[0]
            maskbench_groups[group] += 1

    all_stats_path = metainfo_dir / "all_stats.json"
    all_stats = load_json(all_stats_path)
    all_stats_summary = ""
    if isinstance(all_stats, list):
        valid = sum(int(item.get("num_valid_tests", 0)) for item in all_stats if isinstance(item, dict))
        invalid = sum(int(item.get("num_invalid_tests", 0)) for item in all_stats if isinstance(item, dict))
        no_tests = sum(
            1
            for item in all_stats
            if isinstance(item, dict)
            and int(item.get("num_valid_tests", 0)) + int(item.get("num_invalid_tests", 0)) == 0
        )
        all_stats_summary = (
            f"- Entries: {len(all_stats)}\n"
            f"- Aggregate valid tests: {valid}\n"
            f"- Aggregate invalid tests: {invalid}\n"
            f"- Schemas with zero aggregate tests: {no_tests}\n"
        )
    else:
        all_stats_summary = "- Could not parse all_stats.json\n"

    engine_files = [
        runner_dir / "runner.py",
        runner_dir / "engine.py",
        runner_dir / "llg_engine.py",
        runner_dir / "xgr_engine.py",
        runner_dir / "llamacpp_engine.py",
        runner_dir / "outlines_engine.py",
    ]
    benchmark_scripts = [
        scripts_dir / "run_maskbench.py",
        scripts_dir / "maskbench_results.py",
        scripts_dir / "kill_bench.sh",
    ]
    creation_scripts = sorted(creation_dir.glob("*.py")) if creation_dir.exists() else []
    result_dirs = discover_result_dirs()
    sample = sample_maskbench_file()

    lines: list[str] = []
    lines.append("# Project Structure Report\n")
    lines.append("This report was generated by `extension_jsonschemabench/scripts/discover_project_structure.py`.\n")

    lines.append("## Important Folders\n")
    folders = [
        ("Top-level schema corpus", data_dir),
        ("MaskBench package and benchmark", maskbench_dir),
        ("MaskBench schema/test corpus", maskbench_data_dir),
        ("MaskBench metadata", metainfo_dir),
        ("MaskBench runner and engines", runner_dir),
        ("MaskBench benchmark scripts", scripts_dir),
        ("MaskBench testcase creation scripts", creation_dir),
    ]
    for label, path in folders:
        status = "found" if path.exists() else "not_found"
        lines.append(f"- {label}: `{rel(path)}` ({status})")
    lines.append("")

    lines.append("## Top-Level Schema Corpus\n")
    if dataset_counts:
        lines.append("| Dataset | JSON files |")
        lines.append("| --- | ---: |")
        for name, count in dataset_counts:
            lines.append(f"| `{name}` | {count} |")
    else:
        lines.append("No top-level dataset folders found.")
    lines.append("")

    lines.append("## MaskBench Data Corpus\n")
    lines.append(f"- Direct JSON files: {direct_json_count(maskbench_data_dir)}")
    lines.append(f"- Recursive JSON files: {count_json_files(maskbench_data_dir)}")
    if maskbench_groups:
        lines.append("")
        lines.append("| Group | Files |")
        lines.append("| --- | ---: |")
        for name, count in maskbench_groups.most_common():
            lines.append(f"| `{name}` | {count} |")
    if sample:
        lines.append("")
        lines.append("### Sample Test File Shape\n")
        lines.append(f"- File: `{sample['path']}`")
        lines.append(f"- Top-level keys: `{sample['top_level_keys']}`")
        lines.append(f"- Test count: {sample['test_count']}")
        lines.append(f"- First test keys: `{sample['first_test_keys']}`")
    lines.append("")

    lines.append("## Metadata\n")
    lines.append(f"- Main aggregate file: `{rel(all_stats_path)}`")
    lines.append(all_stats_summary.rstrip())
    lines.append("")

    lines.append("## Runner And Framework Files\n")
    for path in engine_files:
        status = "found" if path.exists() else "not_found"
        lines.append(f"- `{rel(path)}` ({status})")
    lines.append("")
    lines.append("Framework command-line flags are defined in `maskbench/maskbench/runner.py`: "
                 "`--llg`, `--xgr`, `--xgr-compliant`, `--xgr-cpp`, `--llamacpp`, `--outlines`.\n")

    lines.append("## Benchmark Scripts\n")
    for path in benchmark_scripts:
        status = "found" if path.exists() else "not_found"
        lines.append(f"- `{rel(path)}` ({status})")
    lines.append("")

    lines.append("## Testcase Creation Scripts\n")
    if creation_scripts:
        for path in creation_scripts:
            lines.append(f"- `{rel(path)}`")
    else:
        lines.append("No testcase creation scripts found.")
    lines.append("")

    lines.append("## Result Folders\n")
    if result_dirs:
        for path in result_dirs:
            meta = path / "meta.txt"
            status = "meta found" if meta.exists() else "meta not_found"
            lines.append(f"- `{rel(path)}` ({status})")
    else:
        lines.append("No `tmp/out--*` result folders were found in the current checkout.")
    lines.append("")

    lines.append("## Initial Interpretation\n")
    lines.append("- `data/` stores source schemas without individual generated tests.")
    lines.append("- `maskbench/data/*.json` stores the schema plus its individual valid/invalid test instances.")
    lines.append("- `maskbench/metainfo/all_stats.json` stores aggregate counts only, not test-level records.")
    lines.append("- Benchmark result folders, when present, are keyed by schema file name and framework output folder.")
    lines.append("- The current runner records schema-level status and limited `test #<index>` error text, not a complete per-test execution log.")
    lines.append("")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {rel(REPORT_PATH)}")


if __name__ == "__main__":
    main()
